<p>Salut</p>


<div id="formSection">
<form method="post" action="#">
  <div class="form-group">
    <label >Votre Nom</label>
    <input name="name" type="text">
  </div>
 <div class="form-group">
    <label>E-mail</label>
    <input name="email" type="email">
  </div>
  <div class="form-group">
    <label>Message</label>
    <textarea name="message"type="text"></textarea>
  </div>
  <button type = "submit">Envoyer</button>
</form>